%% Task 01: Create IMU Model

% close all
% clear
% clc

% Save figures as *.eps
saveFigureAsEps = @(name, fig)(exportgraphics(fig, fullfile("..", "latex", "images", name)));


%% Task 01: Create IMU Model

% Constants
gravity = 9.81;  


%% Create IMU Model

% Instantiate Empty Class
imu = ImuModel();

% Set Gyroscope Parameters
imu.b_g = [100; 30; -250] * pi/180 / 60^2;
imu.M_g = [...
    450e-6,   -0.0001,  0.0002; ...
    -0.0003,  -300e-6,   0.0004; ...
    -0.0005,  0.0006,  175e-6]; 

% Set Gyro Noise Parameters
ARW = 0.15 * pi/180;
gyroSigma = ARW / 60;
imu.GyroWhiteNoiseOneSigmaX = gyroSigma; 
imu.GyroWhiteNoiseOneSigmaY = gyroSigma; 
imu.GyroWhiteNoiseOneSigmaZ = gyroSigma; 

% Set Accelerometer Parameters
imu.b_a = [...
    6.4e-3 * gravity; ...
    -5.2e-3 * gravity; ...
    3.70e-3 * gravity];
imu.M_a = [...
    150e-6,   0.0001,  -0.0002; ...
    0.0003,  -175e-6,   -0.0004; ...
    0.0005,  -0.0006,  198e-6]; 

% Set Accel Noise Parameters
VRW = 0.07;
accelSigma = VRW / 60;
imu.AccelWhiteNoiseOneSigmaX = accelSigma; 
imu.AccelWhiteNoiseOneSigmaY = accelSigma; 
imu.AccelWhiteNoiseOneSigmaZ = accelSigma; 

% Get True Accelerometer Model
m_accel_true = [...
    imu.AccelFixedBiasX; ...
    imu.AccelScaleFactorErrorX; ...
    imu.AccelMisalignmentXY; ...
    imu.AccelMisalignmentXZ; ...
    imu.AccelFixedBiasY; ...
    imu.AccelMisalignmentYX; ...
    imu.AccelScaleFactorErrorY; ...
    imu.AccelMisalignmentYZ; ...
    imu.AccelFixedBiasZ; ...
    imu.AccelMisalignmentZX; ...
    imu.AccelMisalignmentZY; ...
    imu.AccelScaleFactorErrorZ];

% Get True Gyroscope Model
m_gyro_true = [...
    imu.GyroFixedBiasX; ...
    imu.GyroScaleFactorErrorX; ...
    imu.GyroMisalignmentXY; ...
    imu.GyroMisalignmentXZ; ...
    imu.GyroFixedBiasY; ...
    imu.GyroMisalignmentYX; ...
    imu.GyroScaleFactorErrorY; ...
    imu.GyroMisalignmentYZ; ...
    imu.GyroFixedBiasZ; ...
    imu.GyroMisalignmentZX; ...
    imu.GyroMisalignmentZY; ...
    imu.GyroScaleFactorErrorZ];

%% Tick Labels

% Gyro model labels
gyroModelLabels = {...
    'b_g_,_x', ...
    's_g_,_x', ...
    'm_g_,_x_y', ...
    'm_g_,_x_z', ...
    'b_g_,_y', ...
    'm_g_,_y_x', ...
    's_g_,_y', ...
    'm_g_,_y_z', ...
    'b_g_,_z', ...
    'm_g_,_z_x', ...
    'm_g_,_z_y', ...
    's_g_,_z'};

% Accel model labels
accelModelLabels = {...
    'b_a_,_x', ...
    's_a_,_x', ...
    'm_a_,_x_y', ...
    'm_a_,_x_z', ...
    'b_a_,_y', ...
    'm_a_,_y_x', ...
    's_a_,_y', ...
    'm_a_,_y_z', ...
    'b_a_,_z', ...
    'm_a_,_z_x', ...
    'm_a_,_z_y', ...
    's_a_,_z'};

%% Latex Labels

% Gyro model labels
gyroLatexLabels = {...
    'b_{g,x}', ...
    's_{g,x}', ...
    'm_{g,xy}', ...
    'm_{g,xz}', ...
    'b_{g,y}', ...
    'm_{g,yx}', ...
    's_{g,y}', ...
    'm_{g,yz}', ...
    'b_{g,z}', ...
    'm_{g,zx}', ...
    'm_{g,zy}', ...
    's_{g,z}'};

% Accel model labels
accelLatexLabels = {...
    'b_{a,x}', ...
    's_{a,x}', ...
    'm_{a,xy}', ...
    'm_{a,xz}', ...
    'b_{a,y}', ...
    'm_{a,yx}', ...
    's_{a,y}', ...
    'm_{a,yz}', ...
    'b_{a,z}', ...
    'm_{a,zx}', ...
    'm_{a,zy}', ...
    's_{a,z}'};


%% Create Tables to Store Results

% Gyro Table Results
gyroTable = array2table(m_gyro_true);
gyroTable.Properties.VariableNames = {'TrueModel'};
gyroTable.Properties.RowNames = {...
    'GyroFixedBiasX', ...
    'GyroScaleFactorErrorX', ...
    'GyroMisalignmentXY', ...
    'GyroMisalignmentXZ', ...
    'GyroFixedBiasY', ...
    'GyroMisalignmentYX', ...
    'GyroScaleFactorErrorY', ...
    'GyroMisalignmentYZ', ...
    'GyroFixedBiasZ', ...
    'GyroMisalignmentZX', ...
    'GyroMisalignmentZY', ...
    'GyroScaleFactorErrorZ'};

% Accel Table Results
accelTable = array2table(m_accel_true);
accelTable.Properties.VariableNames = {'TrueModel'};
accelTable.Properties.RowNames = {...
    'AccelFixedBiasX', ...
    'AccelScaleFactorErrorX', ...
    'AccelMisalignmentXY', ...
    'AccelMisalignmentXZ', ...
    'AccelFixedBiasY', ...
    'AccelMisalignmentYX', ...
    'AccelScaleFactorErrorY', ...
    'AccelMisalignmentYZ', ...
    'AccelFixedBiasZ', ...
    'AccelMisalignmentZX', ...
    'AccelMisalignmentZY', ...
    'AccelScaleFactorErrorZ'};


%% Save Data

workingFilePath = fullfile(pwd, "working_file.mat");
save(workingFilePath, ...
    "imu", ...
    "gravity", ...
    "m_gyro_true", ...
    "m_accel_true", ...
    "gyroSigma", ...
    "accelSigma", ...
    "gyroModelLabels", ...
    "accelModelLabels", ...
    "gyroLatexLabels", ...
    "accelLatexLabels", ...
    "gyroTable", ...
    "accelTable", ...
    "workingFilePath")

